<?php

namespace DoctrineORMModule\Proxy\__CG__\Cliente\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cliente extends \Cliente\Entity\Cliente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'idclientes', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'nome', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'cpfcnpj', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'rg', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'ie', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'telefoner', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'telefonec', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'celular1', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'celular2', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'email', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'datanascimento', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'estadocivil', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'observacao');
        }

        return array('__isInitialized__', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'idclientes', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'nome', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'cpfcnpj', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'rg', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'ie', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'telefoner', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'telefonec', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'celular1', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'celular2', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'email', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'datanascimento', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'estadocivil', '' . "\0" . 'Cliente\\Entity\\Cliente' . "\0" . 'observacao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cliente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdclientes()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdclientes();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdclientes', array());

        return parent::getIdclientes();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getCpfcnpj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpfcnpj', array());

        return parent::getCpfcnpj();
    }

    /**
     * {@inheritDoc}
     */
    public function getRg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRg', array());

        return parent::getRg();
    }

    /**
     * {@inheritDoc}
     */
    public function getIe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIe', array());

        return parent::getIe();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefoner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefoner', array());

        return parent::getTelefoner();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonec()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonec', array());

        return parent::getTelefonec();
    }

    /**
     * {@inheritDoc}
     */
    public function getCelular1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCelular1', array());

        return parent::getCelular1();
    }

    /**
     * {@inheritDoc}
     */
    public function getCelular2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCelular2', array());

        return parent::getCelular2();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getDatanascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatanascimento', array());

        return parent::getDatanascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadocivil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadocivil', array());

        return parent::getEstadocivil();
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacao', array());

        return parent::getObservacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getDatacadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatacadastro', array());

        return parent::getDatacadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataupdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataupdate', array());

        return parent::getDataupdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdclientes($idclientes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdclientes', array($idclientes));

        return parent::setIdclientes($idclientes);
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function setCpfcnpj($cpfcnpj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpfcnpj', array($cpfcnpj));

        return parent::setCpfcnpj($cpfcnpj);
    }

    /**
     * {@inheritDoc}
     */
    public function setRg($rg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRg', array($rg));

        return parent::setRg($rg);
    }

    /**
     * {@inheritDoc}
     */
    public function setIe($ie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIe', array($ie));

        return parent::setIe($ie);
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefoner($telefoner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefoner', array($telefoner));

        return parent::setTelefoner($telefoner);
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonec($telefonec)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonec', array($telefonec));

        return parent::setTelefonec($telefonec);
    }

    /**
     * {@inheritDoc}
     */
    public function setCelular1($celular1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCelular1', array($celular1));

        return parent::setCelular1($celular1);
    }

    /**
     * {@inheritDoc}
     */
    public function setCelular2($celular2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCelular2', array($celular2));

        return parent::setCelular2($celular2);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setDatanascimento($datanascimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatanascimento', array($datanascimento));

        return parent::setDatanascimento($datanascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadocivil($estadocivil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadocivil', array($estadocivil));

        return parent::setEstadocivil($estadocivil);
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacao($observacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacao', array($observacao));

        return parent::setObservacao($observacao);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
