<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Prosoft Sistema Gerenciamento Provedor Mikrotik')->setSeparator(' - ')->setAutoEscape(false) ?>
        
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
//                        ->prependStylesheet($this->basePath('css/layout.css'))
                        ->prependStylesheet($this->basePath('css/formulario-input.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('font-awesome/css/font-awesome.min.css'))?>
       
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body style='overflow-y: scroll;'>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                        <ul class="navbar-nav">
                        <li><a class="navbar-brand" style="color: #00CC00; font-weight:bold" href="<?php echo $this->url('application') ?>"><i class="fa fa-gears"></i> ProSoft-MK</a></li>
                    </ul>
                </div>
                
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administração <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">

                                <li><a href="<?php echo $this->url('empresa') ?>">Empresa</a></li>
                                <li><a href="">FranquiaSCM</a></li>
                                <li><a href="">Faixa de Ips</a></li>
                                <li><a href="">Cadastro de Planos</a></li>
                                <li><a href="<?php echo $this->url('usuario') ?>">Usuarios</a></li>  
                                <li class="divider"></li>
                                
                            </ul>
                        </li>
                        
                         <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Patrimônio<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">

                                <li><a href="" onclick="abrir('NFO1');
                                    return false;">Aparelhos</a></li>
                                <li><a href="" onclick="abrir('CO4');
                                        return false;">Fontes</a></li>
                                <li><a href="" onclick="abrir('CO3');
                                        return false;">Baterias</a></li>
                                <li><a href="" onclick="abrir('CO3');
                                        return false;">Cartão</a></li>
                                <li><a href="" onclick="abrir('CO3');
                                        return false;">Antenas</a></li>
                                
                            </ul>
                        </li> 
                        
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Células<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">

                                <li><a href="" onclick="abrir('NFO1');
                                    return false;">Coordenadas</a></li>
                                
                            </ul>
                        </li> 
                        
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Registros<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">

                                <li><a href="" onclick="abrir('NFO1');
                                    return false;">Aparelhos</a></li>
                                <li><a href="" onclick="abrir('CO4');
                                        return false;">Cidade / UF</a></li>
                                <li><a href="" onclick="abrir('CO3');
                                        return false;">Bairro</a></li>
                                
                            </ul>
                        </li> 

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cadastros <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
    
                                
                                <li><a href="<?php echo $this->url('cliente') ?>">Clientes</a></li>
                                <li><a href="" onclick="abrir('NF4');
                                        return false;">Contrato</a></li>
                                <li><a href="" onclick="abrir('NF8');
                                        return false;">Ticket</a></li>
                                
                            </ul>
                        </li>

                        

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Financeiro <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">

                                <li><a href="" onclick="abrir('F1');
                                    return false;">Conta Bancaria</a></li>
                                <li><a href="" onclick="abrir('F2');
                                        return false;">Gerar Boleto</a></li>
                                <li><a href="" onclick="abrir('F3');
                                        return false;">Imprimir Boleto</a></li>
                                <li><a href="" onclick="abrir('F3');
                                        return false;">Imprimir Boleto Avulso   </a></li>
                                <li><a href="" onclick="abrir('F4');
                                        return false;">Enviar Aviso</a></li>
                            </ul>
                        </li> 
                        
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Acessórios<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="" onclick="abrir('U1');
                                        return false;">Agenda</a></li>
                                
<!--                                <li><a href="" onclick="abrir('');
                                    return false;">Emissão Nfe</a></li>
                                <li><a href="" onclick="abrir('');
                                        return false;">Configuração Nfe</a></li>
                                <li><a href="" onclick="abrir('');
                                        return false;">Speed Fiscal</a></li>-->
                            </ul>
                        </li> 
                    </ul>

<!--                    <ul class="nav navbar-nav navbar-right">
                        <form id='logoff' method="post" action="base/login/C_logout.php"  >    
                        </form>
                        <li  ><a href="#" class="usuarioMenu" ><i class="fa fa-user  "></i> <?php //$_SESSION['login'];?> </a></li>
                        <li><a href="#" onclick="destroir();"><i class="fa fa-user"></i></a></li>
                        <li><a href="#" onclick="document.getElementById('logoff').submit();
                                return false;"><i type="submit" class="fa fa-power-off"></i></a></li>
                    </ul>-->
                </div>
                
                
                
                
<!--                
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php //echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div>/.nav-collapse -->
                
                
                
                
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2011 - <?php echo date('Y') ?> SisGew Tecnologia.</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
